"""add relatetion to score

Revision ID: c0e38fbeb6b6
Revises: 5d822aad4c0b
Create Date: 2022-11-15 21:09:43.451150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e38fbeb6b6'
down_revision = '5d822aad4c0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
