"""BOOLean

Revision ID: e7a096608e70
Revises: 7e141d5dc8e0
Create Date: 2022-11-13 20:53:49.976434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a096608e70'
down_revision = '7e141d5dc8e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
